use std::{fs, path::PathBuf};

fn main() {
    let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    if target_os != "android" {
        return;
    }

    // Reuse wry's env vars — dx sets these during the Android build.
    println!("cargo:rerun-if-env-changed=WRY_ANDROID_PACKAGE");
    println!("cargo:rerun-if-env-changed=WRY_ANDROID_KOTLIN_FILES_OUT_DIR");

    let Ok(kotlin_out_dir) = std::env::var("WRY_ANDROID_KOTLIN_FILES_OUT_DIR") else {
        // Not building through dx's android pipeline; nothing to generate.
        return;
    };

    let package = std::env::var("WRY_ANDROID_PACKAGE")
        .expect("WRY_ANDROID_PACKAGE not set — needed to generate FcmService.kt");

    let kotlin_out_dir = PathBuf::from(&kotlin_out_dir)
        .canonicalize()
        .unwrap_or_else(|_| panic!("Failed to canonicalize {kotlin_out_dir}"));

    // ---- Derive the Android app module root from the kotlin out dir ----
    // WRY_ANDROID_KOTLIN_FILES_OUT_DIR typically looks like:
    //   .../<app_module>/app/src/main/kotlin/<package/path>
    // Walk up until we find the "src" directory, then the app module is its parent.
    let app_module = {
        let mut dir = kotlin_out_dir.as_path();
        loop {
            match dir.parent() {
                Some(parent) if dir.file_name().map(|n| n == "src").unwrap_or(false) => {
                    break parent.to_path_buf();
                }
                Some(parent) => dir = parent,
                None => panic!(
                    "Could not locate app module root from {}",
                    kotlin_out_dir.display()
                ),
            }
        }
    };

    // ---- Copy google-services.json into the app module ----
    let gs_src = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap())
        .parent()
        .unwrap() // crates/
        .parent()
        .unwrap() // workspace root
        .join("test-app/android/google-services.json"); // adjust to your actual path

    if gs_src.exists() {
        let gs_dst = app_module.join("google-services.json");
        fs::copy(&gs_src, &gs_dst).ok();
        println!("cargo:rerun-if-changed={}", gs_src.display());
    } else {
        println!(
            "cargo:warning=google-services.json not found at {}",
            gs_src.display()
        );
    }

    // ---- Apply the google-services Gradle plugin (auto-init from google-services.json) ----
    // AndroidArtifactMetadata injects `implementation(...)` deps but NOT the
    // `plugins {}` block or the buildscript classpath, so we wire those two here.
    // No Firebase values are hardcoded — the plugin reads everything from
    // google-services.json at build time.
    apply_google_services_plugin(&app_module);

    // Call the new function here:
    enable_build_config(&app_module);

    // ---- Generate Kotlin files from templates ----
    let template_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap()).join("src/android/kotlin");
    println!("cargo:rerun-if-changed={}", template_dir.display());

    for entry in fs::read_dir(&template_dir).expect("failed to read kotlin template dir") {
        let file = entry.unwrap();

        let content = fs::read_to_string(file.path())
            .expect("failed to read kotlin template")
            .replace("{{package}}", &package)
            .replace("{{package-unescaped}}", &package.replace('`', ""));

        let out = format!(
            "/* THIS FILE IS AUTO-GENERATED BY dioxus-fcm. DO NOT MODIFY!! */\n\n{content}"
        );

        let out_path = kotlin_out_dir.join(file.file_name());
        if fs::read_to_string(&out_path).map_or(true, |o| o != out) {
            fs::write(&out_path, &out).expect("failed to write generated kotlin");
        }
        println!("cargo:rerun-if-changed={}", out_path.display());
    }
}

/// Inject the `com.google.gms.google-services` plugin into the generated Gradle
/// project. Idempotent: safe to run on every build (dx regenerates these files).
///
/// - project `build.gradle.kts`: add the plugin classpath to `buildscript { dependencies }`
/// - app `build.gradle.kts`: apply the plugin in the top-level `plugins { }` block
fn apply_google_services_plugin(app_module: &std::path::Path) {
    const GS_VERSION: &str = "4.4.2";

    // app_module = .../android/app/app
    // project root (has the buildscript) = .../android/app
    let project_root = app_module
        .parent()
        .expect("app module has no parent (project root)")
        .to_path_buf();

    let app_gradle = app_module.join("build.gradle.kts");
    let root_gradle = project_root.join("build.gradle.kts");

    // 1. Add the plugin classpath to the project buildscript.
    match fs::read_to_string(&root_gradle) {
        Ok(mut contents) => {
            if !contents.contains("com.google.gms:google-services") {
                let needle = "classpath(\"org.jetbrains.kotlin:kotlin-gradle-plugin";
                if let Some(pos) = contents.find(needle) {
                    let insert = format!(
                        "classpath(\"com.google.gms:google-services:{GS_VERSION}\")\n        "
                    );
                    contents.insert_str(pos, &insert);
                    fs::write(&root_gradle, contents)
                        .expect("failed to write project build.gradle.kts");
                } else {
                    println!(
                        "cargo:warning=could not find kotlin-gradle-plugin classpath in {}; \
                         google-services classpath not injected",
                        root_gradle.display()
                    );
                }
            }
        }
        Err(e) => println!(
            "cargo:warning=could not read {}: {e}",
            root_gradle.display()
        ),
    }

    // 2. Apply the plugin in the app module's plugins block.
    match fs::read_to_string(&app_gradle) {
        Ok(mut contents) => {
            if !contents.contains("com.google.gms.google-services") {
                let needle = "id(\"org.jetbrains.kotlin.android\")";
                if let Some(pos) = contents.find(needle) {
                    let end = pos + needle.len();
                    let insert = "\n    id(\"com.google.gms.google-services\")";
                    contents.insert_str(end, insert);
                    fs::write(&app_gradle, contents).expect("failed to write app build.gradle.kts");
                } else {
                    println!(
                        "cargo:warning=could not find kotlin.android plugin id in {}; \
                         google-services plugin not applied",
                        app_gradle.display()
                    );
                }
            }
        }
        Err(e) => println!("cargo:warning=could not read {}: {e}", app_gradle.display()),
    }
}
// Add this call to your main() function:
// apply_google_services_plugin(&app_module);
// enable_build_config(&app_module);

fn enable_build_config(app_module: &std::path::Path) {
    let app_gradle = app_module.join("build.gradle.kts");

    match fs::read_to_string(&app_gradle) {
        Ok(mut contents) => {
            // Check if buildConfig is already enabled to avoid duplicate injections
            if !contents.contains("buildConfig = true") {
                // We look for the 'android {' block to insert our configuration
                let needle = "android {";
                if let Some(pos) = contents.find(needle) {
                    let end = pos + needle.len();
                    let insert = "\n    buildFeatures {\n        buildConfig = true\n    }";

                    contents.insert_str(end, insert);
                    fs::write(&app_gradle, contents)
                        .expect("failed to write app build.gradle.kts (buildConfig)");
                    println!("cargo:warning=Successfully injected buildConfig = true");
                } else {
                    println!(
                        "cargo:warning=Could not find 'android {{' block in {}",
                        app_gradle.display()
                    );
                }
            }
        }
        Err(e) => println!("cargo:warning=Could not read {}: {e}", app_gradle.display()),
    }
}
